version: '3.3'

services:
  mysqldb:
    image: mysql
    restart: unless-stopped
    env_file: ./application/.env
    environment:
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./application
    restart: unless-stopped
    env_file: ./application/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true

volumes: 
  db: